// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/cdc_sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation types matching MSSQL CDC __$operation values
type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_TYPE_DELETE      OperationType = 1 // __$operation = 1
	OperationType_OPERATION_TYPE_INSERT      OperationType = 2 // __$operation = 2
	OperationType_OPERATION_TYPE_UPDATE_OLD  OperationType = 3 // __$operation = 3 (before image)
	OperationType_OPERATION_TYPE_UPDATE_NEW  OperationType = 4 // __$operation = 4 (after image)
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_DELETE",
		2: "OPERATION_TYPE_INSERT",
		3: "OPERATION_TYPE_UPDATE_OLD",
		4: "OPERATION_TYPE_UPDATE_NEW",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_DELETE":      1,
		"OPERATION_TYPE_INSERT":      2,
		"OPERATION_TYPE_UPDATE_OLD":  3,
		"OPERATION_TYPE_UPDATE_NEW":  4,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cdc_sync_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_cdc_sync_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_cdc_sync_proto_rawDescGZIP(), []int{0}
}

// Acknowledgment status codes
type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED     AckStatus = 0
	AckStatus_ACK_STATUS_OK              AckStatus = 1 // All changes applied successfully
	AckStatus_ACK_STATUS_PARTIAL         AckStatus = 2 // Some changes applied (check last_sequence_number)
	AckStatus_ACK_STATUS_RETRY           AckStatus = 3 // Transient error, source should retry
	AckStatus_ACK_STATUS_FAILED          AckStatus = 4 // Permanent failure, manual intervention needed
	AckStatus_ACK_STATUS_SCHEMA_MISMATCH AckStatus = 5 // Schema incompatibility detected
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_OK",
		2: "ACK_STATUS_PARTIAL",
		3: "ACK_STATUS_RETRY",
		4: "ACK_STATUS_FAILED",
		5: "ACK_STATUS_SCHEMA_MISMATCH",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED":     0,
		"ACK_STATUS_OK":              1,
		"ACK_STATUS_PARTIAL":         2,
		"ACK_STATUS_RETRY":           3,
		"ACK_STATUS_FAILED":          4,
		"ACK_STATUS_SCHEMA_MISMATCH": 5,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cdc_sync_proto_enumTypes[1].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_proto_cdc_sync_proto_enumTypes[1]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_cdc_sync_proto_rawDescGZIP(), []int{1}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING_STATUS_UNSPECIFIED HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING_STATUS_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_SERVING_STATUS_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cdc_sync_proto_enumTypes[2].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_proto_cdc_sync_proto_enumTypes[2]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_cdc_sync_proto_rawDescGZIP(), []int{4, 0}
}

// Represents a single CDC change event
type ChangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this change batch
	BatchId string `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// The LSN (Log Sequence Number) from MSSQL CDC
	Lsn []byte `protobuf:"bytes,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	// Sequence number within the batch
	SequenceNumber uint64 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// The operation type
	Operation OperationType `protobuf:"varint,4,opt,name=operation,proto3,enum=cdc_sync.OperationType" json:"operation,omitempty"`
	// Target schema and table
	SchemaName string `protobuf:"bytes,5,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	TableName  string `protobuf:"bytes,6,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// Primary key columns and their values (JSON encoded)
	PrimaryKeyJson string `protobuf:"bytes,7,opt,name=primary_key_json,json=primaryKeyJson,proto3" json:"primary_key_json,omitempty"`
	// The row data (JSON encoded for flexibility)
	// For DELETE operations, this contains the old values
	// For INSERT/UPDATE, this contains the new values
	RowDataJson string `protobuf:"bytes,8,opt,name=row_data_json,json=rowDataJson,proto3" json:"row_data_json,omitempty"`
	// For UPDATE operations, the previous values
	OldRowDataJson *string `protobuf:"bytes,9,opt,name=old_row_data_json,json=oldRowDataJson,proto3,oneof" json:"old_row_data_json,omitempty"`
	// Timestamp when the change occurred in source DB
	SourceTimestamp *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=source_timestamp,json=sourceTimestamp,proto3" json:"source_timestamp,omitempty"`
	// Column metadata for schema validation
	Columns       []*ColumnMetadata `protobuf:"bytes,11,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest) Reset() {
	*x = ChangeRequest{}
	mi := &file_proto_cdc_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest) ProtoMessage() {}

func (x *ChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdc_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest.ProtoReflect.Descriptor instead.
func (*ChangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdc_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *ChangeRequest) GetLsn() []byte {
	if x != nil {
		return x.Lsn
	}
	return nil
}

func (x *ChangeRequest) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ChangeRequest) GetOperation() OperationType {
	if x != nil {
		return x.Operation
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *ChangeRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *ChangeRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ChangeRequest) GetPrimaryKeyJson() string {
	if x != nil {
		return x.PrimaryKeyJson
	}
	return ""
}

func (x *ChangeRequest) GetRowDataJson() string {
	if x != nil {
		return x.RowDataJson
	}
	return ""
}

func (x *ChangeRequest) GetOldRowDataJson() string {
	if x != nil && x.OldRowDataJson != nil {
		return *x.OldRowDataJson
	}
	return ""
}

func (x *ChangeRequest) GetSourceTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceTimestamp
	}
	return nil
}

func (x *ChangeRequest) GetColumns() []*ColumnMetadata {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Column metadata for schema awareness
type ColumnMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	IsNullable    bool                   `protobuf:"varint,3,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	IsPrimaryKey  bool                   `protobuf:"varint,4,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,5,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	Precision     *int32                 `protobuf:"varint,6,opt,name=precision,proto3,oneof" json:"precision,omitempty"`
	Scale         *int32                 `protobuf:"varint,7,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnMetadata) Reset() {
	*x = ColumnMetadata{}
	mi := &file_proto_cdc_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMetadata) ProtoMessage() {}

func (x *ColumnMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdc_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMetadata.ProtoReflect.Descriptor instead.
func (*ColumnMetadata) Descriptor() ([]byte, []int) {
	return file_proto_cdc_sync_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnMetadata) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ColumnMetadata) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *ColumnMetadata) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *ColumnMetadata) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *ColumnMetadata) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *ColumnMetadata) GetScale() int32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

// Acknowledgment from Target to Source
type ChangeAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The batch_id being acknowledged
	BatchId string `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// The LSN being acknowledged (Source can advance cursor past this)
	Lsn []byte `protobuf:"bytes,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	// Highest sequence number successfully processed in this batch
	LastSequenceNumber uint64 `protobuf:"varint,3,opt,name=last_sequence_number,json=lastSequenceNumber,proto3" json:"last_sequence_number,omitempty"`
	// Acknowledgment status
	Status AckStatus `protobuf:"varint,4,opt,name=status,proto3,enum=cdc_sync.AckStatus" json:"status,omitempty"`
	// Error message if status is not OK
	ErrorMessage *string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// Number of rows successfully processed
	RowsProcessed uint64 `protobuf:"varint,6,opt,name=rows_processed,json=rowsProcessed,proto3" json:"rows_processed,omitempty"`
	// Processing duration in milliseconds
	ProcessingTimeMs uint64 `protobuf:"varint,7,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChangeAck) Reset() {
	*x = ChangeAck{}
	mi := &file_proto_cdc_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAck) ProtoMessage() {}

func (x *ChangeAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdc_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAck.ProtoReflect.Descriptor instead.
func (*ChangeAck) Descriptor() ([]byte, []int) {
	return file_proto_cdc_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *ChangeAck) GetLsn() []byte {
	if x != nil {
		return x.Lsn
	}
	return nil
}

func (x *ChangeAck) GetLastSequenceNumber() uint64 {
	if x != nil {
		return x.LastSequenceNumber
	}
	return 0
}

func (x *ChangeAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *ChangeAck) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *ChangeAck) GetRowsProcessed() uint64 {
	if x != nil {
		return x.RowsProcessed
	}
	return 0
}

func (x *ChangeAck) GetProcessingTimeMs() uint64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_cdc_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdc_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_cdc_sync_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=cdc_sync.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Version       string                            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ServerTime    *timestamppb.Timestamp            `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_cdc_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cdc_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_cdc_sync_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_proto_cdc_sync_proto protoreflect.FileDescriptor

const file_proto_cdc_sync_proto_rawDesc = "" +
	"\n" +
	"\x14proto/cdc_sync.proto\x12\bcdc_sync\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x03\n" +
	"\rChangeRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x10\n" +
	"\x03lsn\x18\x02 \x01(\fR\x03lsn\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\x125\n" +
	"\toperation\x18\x04 \x01(\x0e2\x17.cdc_sync.OperationTypeR\toperation\x12\x1f\n" +
	"\vschema_name\x18\x05 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x06 \x01(\tR\ttableName\x12(\n" +
	"\x10primary_key_json\x18\a \x01(\tR\x0eprimaryKeyJson\x12\"\n" +
	"\rrow_data_json\x18\b \x01(\tR\vrowDataJson\x12.\n" +
	"\x11old_row_data_json\x18\t \x01(\tH\x00R\x0eoldRowDataJson\x88\x01\x01\x12E\n" +
	"\x10source_timestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0fsourceTimestamp\x122\n" +
	"\acolumns\x18\v \x03(\v2\x18.cdc_sync.ColumnMetadataR\acolumnsB\x14\n" +
	"\x12_old_row_data_json\"\x91\x02\n" +
	"\x0eColumnMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1f\n" +
	"\vis_nullable\x18\x03 \x01(\bR\n" +
	"isNullable\x12$\n" +
	"\x0eis_primary_key\x18\x04 \x01(\bR\fisPrimaryKey\x12\"\n" +
	"\n" +
	"max_length\x18\x05 \x01(\x05H\x00R\tmaxLength\x88\x01\x01\x12!\n" +
	"\tprecision\x18\x06 \x01(\x05H\x01R\tprecision\x88\x01\x01\x12\x19\n" +
	"\x05scale\x18\a \x01(\x05H\x02R\x05scale\x88\x01\x01B\r\n" +
	"\v_max_lengthB\f\n" +
	"\n" +
	"_precisionB\b\n" +
	"\x06_scale\"\xa8\x02\n" +
	"\tChangeAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x10\n" +
	"\x03lsn\x18\x02 \x01(\fR\x03lsn\x120\n" +
	"\x14last_sequence_number\x18\x03 \x01(\x04R\x12lastSequenceNumber\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.cdc_sync.AckStatusR\x06status\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12%\n" +
	"\x0erows_processed\x18\x06 \x01(\x04R\rrowsProcessed\x12,\n" +
	"\x12processing_time_ms\x18\a \x01(\x04R\x10processingTimeMsB\x10\n" +
	"\x0e_error_message\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\x9e\x02\n" +
	"\x13HealthCheckResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.cdc_sync.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"k\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02*\xa3\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_TYPE_DELETE\x10\x01\x12\x19\n" +
	"\x15OPERATION_TYPE_INSERT\x10\x02\x12\x1d\n" +
	"\x19OPERATION_TYPE_UPDATE_OLD\x10\x03\x12\x1d\n" +
	"\x19OPERATION_TYPE_UPDATE_NEW\x10\x04*\x9f\x01\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACK_STATUS_OK\x10\x01\x12\x16\n" +
	"\x12ACK_STATUS_PARTIAL\x10\x02\x12\x14\n" +
	"\x10ACK_STATUS_RETRY\x10\x03\x12\x15\n" +
	"\x11ACK_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aACK_STATUS_SCHEMA_MISMATCH\x10\x052\x98\x01\n" +
	"\aCdcSync\x12A\n" +
	"\rStreamChanges\x12\x17.cdc_sync.ChangeRequest\x1a\x13.cdc_sync.ChangeAck(\x010\x01\x12J\n" +
	"\vHealthCheck\x12\x1c.cdc_sync.HealthCheckRequest\x1a\x1d.cdc_sync.HealthCheckResponseB$Z\"github.com/wso2/db-sync-tool/protob\x06proto3"

var (
	file_proto_cdc_sync_proto_rawDescOnce sync.Once
	file_proto_cdc_sync_proto_rawDescData []byte
)

func file_proto_cdc_sync_proto_rawDescGZIP() []byte {
	file_proto_cdc_sync_proto_rawDescOnce.Do(func() {
		file_proto_cdc_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cdc_sync_proto_rawDesc), len(file_proto_cdc_sync_proto_rawDesc)))
	})
	return file_proto_cdc_sync_proto_rawDescData
}

var file_proto_cdc_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_cdc_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_cdc_sync_proto_goTypes = []any{
	(OperationType)(0),                     // 0: cdc_sync.OperationType
	(AckStatus)(0),                         // 1: cdc_sync.AckStatus
	(HealthCheckResponse_ServingStatus)(0), // 2: cdc_sync.HealthCheckResponse.ServingStatus
	(*ChangeRequest)(nil),                  // 3: cdc_sync.ChangeRequest
	(*ColumnMetadata)(nil),                 // 4: cdc_sync.ColumnMetadata
	(*ChangeAck)(nil),                      // 5: cdc_sync.ChangeAck
	(*HealthCheckRequest)(nil),             // 6: cdc_sync.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 7: cdc_sync.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_proto_cdc_sync_proto_depIdxs = []int32{
	0, // 0: cdc_sync.ChangeRequest.operation:type_name -> cdc_sync.OperationType
	8, // 1: cdc_sync.ChangeRequest.source_timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: cdc_sync.ChangeRequest.columns:type_name -> cdc_sync.ColumnMetadata
	1, // 3: cdc_sync.ChangeAck.status:type_name -> cdc_sync.AckStatus
	2, // 4: cdc_sync.HealthCheckResponse.status:type_name -> cdc_sync.HealthCheckResponse.ServingStatus
	8, // 5: cdc_sync.HealthCheckResponse.server_time:type_name -> google.protobuf.Timestamp
	3, // 6: cdc_sync.CdcSync.StreamChanges:input_type -> cdc_sync.ChangeRequest
	6, // 7: cdc_sync.CdcSync.HealthCheck:input_type -> cdc_sync.HealthCheckRequest
	5, // 8: cdc_sync.CdcSync.StreamChanges:output_type -> cdc_sync.ChangeAck
	7, // 9: cdc_sync.CdcSync.HealthCheck:output_type -> cdc_sync.HealthCheckResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_cdc_sync_proto_init() }
func file_proto_cdc_sync_proto_init() {
	if File_proto_cdc_sync_proto != nil {
		return
	}
	file_proto_cdc_sync_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_cdc_sync_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_cdc_sync_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cdc_sync_proto_rawDesc), len(file_proto_cdc_sync_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cdc_sync_proto_goTypes,
		DependencyIndexes: file_proto_cdc_sync_proto_depIdxs,
		EnumInfos:         file_proto_cdc_sync_proto_enumTypes,
		MessageInfos:      file_proto_cdc_sync_proto_msgTypes,
	}.Build()
	File_proto_cdc_sync_proto = out.File
	file_proto_cdc_sync_proto_goTypes = nil
	file_proto_cdc_sync_proto_depIdxs = nil
}
