// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/cdc_sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CdcSync_StreamChanges_FullMethodName = "/cdc_sync.CdcSync/StreamChanges"
	CdcSync_HealthCheck_FullMethodName   = "/cdc_sync.CdcSync/HealthCheck"
)

// CdcSyncClient is the client API for CdcSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The CDC synchronization service using bidirectional streaming
// for reliable change delivery with acknowledgments.
type CdcSyncClient interface {
	// Bidirectional streaming RPC for CDC changes.
	// Source streams changes, Target streams acknowledgments.
	StreamChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeRequest, ChangeAck], error)
	// Health check endpoint
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type cdcSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewCdcSyncClient(cc grpc.ClientConnInterface) CdcSyncClient {
	return &cdcSyncClient{cc}
}

func (c *cdcSyncClient) StreamChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeRequest, ChangeAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CdcSync_ServiceDesc.Streams[0], CdcSync_StreamChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeRequest, ChangeAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CdcSync_StreamChangesClient = grpc.BidiStreamingClient[ChangeRequest, ChangeAck]

func (c *cdcSyncClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CdcSync_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CdcSyncServer is the server API for CdcSync service.
// All implementations must embed UnimplementedCdcSyncServer
// for forward compatibility.
//
// The CDC synchronization service using bidirectional streaming
// for reliable change delivery with acknowledgments.
type CdcSyncServer interface {
	// Bidirectional streaming RPC for CDC changes.
	// Source streams changes, Target streams acknowledgments.
	StreamChanges(grpc.BidiStreamingServer[ChangeRequest, ChangeAck]) error
	// Health check endpoint
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedCdcSyncServer()
}

// UnimplementedCdcSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCdcSyncServer struct{}

func (UnimplementedCdcSyncServer) StreamChanges(grpc.BidiStreamingServer[ChangeRequest, ChangeAck]) error {
	return status.Error(codes.Unimplemented, "method StreamChanges not implemented")
}
func (UnimplementedCdcSyncServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCdcSyncServer) mustEmbedUnimplementedCdcSyncServer() {}
func (UnimplementedCdcSyncServer) testEmbeddedByValue()                 {}

// UnsafeCdcSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CdcSyncServer will
// result in compilation errors.
type UnsafeCdcSyncServer interface {
	mustEmbedUnimplementedCdcSyncServer()
}

func RegisterCdcSyncServer(s grpc.ServiceRegistrar, srv CdcSyncServer) {
	// If the following call panics, it indicates UnimplementedCdcSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CdcSync_ServiceDesc, srv)
}

func _CdcSync_StreamChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CdcSyncServer).StreamChanges(&grpc.GenericServerStream[ChangeRequest, ChangeAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CdcSync_StreamChangesServer = grpc.BidiStreamingServer[ChangeRequest, ChangeAck]

func _CdcSync_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcSyncServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdcSync_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcSyncServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CdcSync_ServiceDesc is the grpc.ServiceDesc for CdcSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CdcSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdc_sync.CdcSync",
	HandlerType: (*CdcSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _CdcSync_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChanges",
			Handler:       _CdcSync_StreamChanges_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/cdc_sync.proto",
}
